backend:
  name: github
  repo: lenanguyen/personal-blog

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - {
          name: cover_photo,
          label: Cover Photo,
          widget: image,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
  - name: goal_tags
    label: Goal Tags
    folder: content/goal_tags
    create: true
    fields:
      - { name: name, label: Name }
  - name: goals
    label: Goals
    folder: content/goals
    create: true
    fields:
      - { name: title, label: title, widget: string }
      - {
          name: list,
          label: List,
          widget: list,
          types:
            [
              {
                label: Quantitative,
                name: quantitative,
                widget: object,
                summary: "{{fields.title}}",
                fields:
                  [
                    { label: Title, name: title, widget: string },
                    { label: Total, name: total, widget: number, default: 0 },
                    {
                      label: Number Complete,
                      name: num_complete,
                      widget: number,
                      min: 0,
                      step: 1,
                      default: 0,
                    },
                    {
                      label: Tags,
                      name: tags,
                      widget: relation,
                      collection: goal_tags,
                      searchFields: [name],
                      valueField: name,
                      multiple: true,
                    },
                  ],
              },
              {
                label: Binary,
                name: binary,
                widget: object,
                summary: "{{fields.title}}",
                fields:
                  [
                    { label: Title, name: title, widget: string },
                    {
                      label: Completed,
                      name: completed,
                      widget: boolean,
                      required: false,
                    },
                    {
                      label: Tags,
                      name: tags,
                      widget: relation,
                      collection: goal_tags,
                      searchFields: [name],
                      valueField: name,
                      multiple: true,
                    },
                  ],
              },
              {
                label: Qualitative,
                name: qualitative,
                summary: "{{fields.title}}",
                fields:
                  [
                    { label: Title, name: title, widget: string },
                    {
                      label: Status,
                      name: status,
                      widget: select,
                      options: ["1", "2", "3", "4", "5"],
                    },
                    {
                      label: Tags,
                      name: tags,
                      widget: relation,
                      collection: goal_tags,
                      searchFields: [name],
                      valueField: name,
                      multiple: true,
                    },
                  ],
              },
            ],
        }
